### PR TITLE
Improvments

### PR DESCRIPTION
**Pull request by jD91mZM2**
No comment. :stuck_out_tongue:

### CODE REVIEW

**Comment by jD91mZM2** [comment]
@bwmarrin BUMP :/

**Comment by bwmarrin** [comment]
I saw it! I just haven't got to.. really look yet.

**Comment by jD91mZM2** [comment]
:clock10:

**Comment by jD91mZM2** [comment]
BUMP?

**Comment by jD91mZM2** [comment]
Ey, awesome seeing you active again @bwmarrin :smile:

Welcome back!

**Comment by bwmarrin** [comment]
I have a lot of catching up to do.. :) For example this whole repo needs deleted and re-made differently!

**Pull request merged**
